server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:fansy001/microservicecloud-config.git
          uri: https://github.com/fansy001/microservicecloud-config.git #GitHub上面的git仓库名字   #用户名密码：fansy001/Fansy8933436266
